export const userTypes = {
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_OUT:'SIGN_OUT'
    

};

export const historyTakingQTypes = {
    CREATE_CASE_Q : 'CREATE_CASE_Q',
    SETCOUNT:'SETCOUNT',
    ALLHISTORYTAKINGQ:'ALLHISTORYTAKINGQ',
    SECTIONORDER: 'SECTIONORDER',
    CLEARHISTORYQ:'CLEARHISTORYQ'
};

export const DentalSheetTypes ={
    CARIES :'CARIES',
    RESTORATION :'RESTORATION',
    CLEARHISTORYDS:'CLEARHISTORYDS'
}
export const caseTypes ={
    SETCASE :'SETCASE',
    SETALLCASES :'SETALLCASES',
    CLEARHISTORYCT:'CLEARHISTORYCT'
}

export const diagnosisTypes ={
    SETDIAGNOSISQ:'SETDIAGNOSISQ',
    SELECTEDANSFORDQ:'SELECTEDANSFORDQ',
    SETCORRECTDIAGNOSISQ:'SETCORRECTDIAGNOSISQ',
    SETWRONGDIAGNOSISQ:'SETWRONGDIAGNOSISQ',
    ISSUBMITDIAGNOSIS:'ISSUBMITDIAGNOSIS',
    CORRECTREMOVE:'CORRECTREMOVE',
    WRONGREMOVE:'WRONGREMOVE',
    CLEARHISTORYDT:'CLEARHISTORYDT'
}

export const scoreTypes={
    DIAG_SCORE : 'IAG_SCORE',
    EXAM_SCORE:'EXAM_SCORE',
    INVEST_SCORE:'INVEST_SCORE',
    HIST_SCORE:'HIST_SCORE',
    PERIODENTAL_SCORE:'PERIODENTAL_SCORE',
    HARDTISSUE_SCORE:'HARDTISSUE_SCORE',
    CARIES_SCORE:'CARIES_SCORE',
    RESTORATION_SCORE:'RESTORATION_SCORE',
    PLAQUE_SCORE:'PLAQUE_SCORE',
    BLEEDING_SCORE:'BLEEDING_SCORE',
    PLAQUE_TOOl_SCORE:'PLAQUE_TOOL_SCORE',
    BLEEDING_TOOl_SCORE:'BLEEDING_TOOL_SCORE',
    RADIO_SCORE:'RADIO_SCORE',
    CLEARHISTORYST:'CLEARHISTORYST'

}
export const examTypes={
    PERIODENTALTOOLS:'PERIODENTALTOOLS',
    PERIO_SUBMIT:'PERIO_SUBMIT',
    HARDTISSUETOOLS:'HARDTISSUETOOLS',
    HARDTISSUE_SUBMIT:'HARDTISSUE_SUBMIT',
    SELECTEDCARIES:'SELECTEDCARIES',
    SELECTEDRESTORATIONS:'SELECTEDRESTORATIONS',
    CLEARCARIES:'CLEARCARIES',
    CLEARRESTO:'CLEARRESTO',
    PLAQUEVAL:'PLAQUEVAL',
    BLEEDINGVAL:'BLEEDINGVAL',
    PERIOTOOLCHECKBOX:'PERIOTOOLCHECKBOX',
    HARDTOOLCHECKBOX:'HARDTOOLCHECKBOX',
    CLEARHISTORYET:'CLEARHISTORYET',
    NEWSETCARRIES:'NEWSETCARRIES',
    NEWSETRESTO:'NEWSETRESTO'
}

export const investTypes={
    RADIOSELECTION:'RADIOSELECTION',
    CLEARHISTORYIT:'CLEARHISTORYIT'
}

export const timeTypes={
    STARTTIME:'STARTTIME',
    CLEARHISTORYTT:'CLEARHISTORYTT'
}